//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODYSHPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InsuranceCmpMaster
    {
        public long InsuranceCompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DealerId { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
