//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODYSHPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPhotoDtl
    {
        public long PhotoId { get; set; }
        public Nullable<long> JobCardId { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
