//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODYSHPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblStatu()
        {
            this.TblJobCardDtls = new HashSet<TblJobCardDtl>();
        }
    
        public long StatusID { get; set; }
        public string StatusName { get; set; }
        public string ShortName { get; set; }
        public string StatusCode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DealerId { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblJobCardDtl> TblJobCardDtls { get; set; }
    }
}
