//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODYSHPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVehicle
    {
        public long VehicleID { get; set; }
        public string VehicleName { get; set; }
        public long BrandID { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
    }
}
